/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { FactoryDeploy, FactoryDeployInterface } from "../FactoryDeploy";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "risky",
        type: "address",
      },
      {
        internalType: "address",
        name: "riskless",
        type: "address",
      },
    ],
    name: "deploy",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "factory",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "factory_",
        type: "address",
      },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "name",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506102ba806100206000396000f3fe608060405234801561001057600080fd5b506004361061004c5760003560e01c806306fdde0314610051578063545e7c6114610099578063c45a0155146100ae578063c4d66de8146100d9575b600080fd5b604080518082018252600d81527f466163746f72794465706c6f7900000000000000000000000000000000000000602082015290516100909190610240565b60405180910390f35b6100ac6100a7366004610207565b610121565b005b6000546100c1906001600160a01b031681565b6040516001600160a01b039091168152602001610090565b6100ac6100e73660046101c6565b600080547fffffffffffffffffffffffff0000000000000000000000000000000000000000166001600160a01b0392909216919091179055565b6000546040517f545e7c610000000000000000000000000000000000000000000000000000000081526001600160a01b03848116600483015283811660248301529091169063545e7c6190604401602060405180830381600087803b15801561018957600080fd5b505af115801561019d573d6000803e3d6000fd5b505050506040513d601f19601f820116820180604052508101906101c191906101ea565b505050565b6000602082840312156101d857600080fd5b81356101e381610295565b9392505050565b6000602082840312156101fc57600080fd5b81516101e381610295565b6000806040838503121561021a57600080fd5b823561022581610295565b9150602083013561023581610295565b809150509250929050565b600060208083528351808285015260005b8181101561026d57858101830151858201604001528201610251565b8181111561027f576000604083870101525b50601f01601f1916929092016040019392505050565b6001600160a01b03811681146102aa57600080fd5b5056fea164736f6c6343000806000a";

export class FactoryDeploy__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<FactoryDeploy> {
    return super.deploy(overrides || {}) as Promise<FactoryDeploy>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): FactoryDeploy {
    return super.attach(address) as FactoryDeploy;
  }
  connect(signer: Signer): FactoryDeploy__factory {
    return super.connect(signer) as FactoryDeploy__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): FactoryDeployInterface {
    return new utils.Interface(_abi) as FactoryDeployInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): FactoryDeploy {
    return new Contract(address, _abi, signerOrProvider) as FactoryDeploy;
  }
}
