/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IManagerBase, IManagerBaseInterface } from "../IManagerBase";

const _abi = [
  {
    inputs: [],
    name: "NotEngineError",
    type: "error",
  },
  {
    inputs: [],
    name: "WrongConstructorParametersError",
    type: "error",
  },
  {
    inputs: [],
    name: "WETH9",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "factory",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "positionDescriptor",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IManagerBase__factory {
  static readonly abi = _abi;
  static createInterface(): IManagerBaseInterface {
    return new utils.Interface(_abi) as IManagerBaseInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IManagerBase {
    return new Contract(address, _abi, signerOrProvider) as IManagerBase;
  }
}
