/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IPrimitiveDepositCallback,
  IPrimitiveDepositCallbackInterface,
} from "../IPrimitiveDepositCallback";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "delRisky",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "delStable",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "depositCallback",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IPrimitiveDepositCallback__factory {
  static readonly abi = _abi;
  static createInterface(): IPrimitiveDepositCallbackInterface {
    return new utils.Interface(_abi) as IPrimitiveDepositCallbackInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPrimitiveDepositCallback {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IPrimitiveDepositCallback;
  }
}
