/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { ISwapManager, ISwapManagerInterface } from "../ISwapManager";

const _abi = [
  {
    inputs: [],
    name: "DeadlineReachedError",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "payer",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "engine",
        type: "address",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "poolId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "riskyForStable",
        type: "bool",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "deltaIn",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "deltaOut",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "fromMargin",
        type: "bool",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "toMargin",
        type: "bool",
      },
    ],
    name: "Swap",
    type: "event",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "recipient",
            type: "address",
          },
          {
            internalType: "address",
            name: "risky",
            type: "address",
          },
          {
            internalType: "address",
            name: "stable",
            type: "address",
          },
          {
            internalType: "bytes32",
            name: "poolId",
            type: "bytes32",
          },
          {
            internalType: "bool",
            name: "riskyForStable",
            type: "bool",
          },
          {
            internalType: "uint256",
            name: "deltaIn",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "deltaOut",
            type: "uint256",
          },
          {
            internalType: "bool",
            name: "fromMargin",
            type: "bool",
          },
          {
            internalType: "bool",
            name: "toMargin",
            type: "bool",
          },
          {
            internalType: "uint256",
            name: "deadline",
            type: "uint256",
          },
        ],
        internalType: "struct ISwapManager.SwapParams",
        name: "params",
        type: "tuple",
      },
    ],
    name: "swap",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "delRisky",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "delStable",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "swapCallback",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ISwapManager__factory {
  static readonly abi = _abi;
  static createInterface(): ISwapManagerInterface {
    return new utils.Interface(_abi) as ISwapManagerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISwapManager {
    return new Contract(address, _abi, signerOrProvider) as ISwapManager;
  }
}
