/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  TestDepositCallback,
  TestDepositCallbackInterface,
} from "../TestDepositCallback";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "dRisky",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "dStable",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "depositCallback",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getCaller",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "risky",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "scenario",
    outputs: [
      {
        internalType: "enum Scenarios.Scenario",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "stable",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class TestDepositCallback__factory {
  static readonly abi = _abi;
  static createInterface(): TestDepositCallbackInterface {
    return new utils.Interface(_abi) as TestDepositCallbackInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): TestDepositCallback {
    return new Contract(address, _abi, signerOrProvider) as TestDepositCallback;
  }
}
