/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface SwapManagerInterface extends ethers.utils.Interface {
  functions: {
    "WETH9()": FunctionFragment;
    "deposit(address,address,address,uint256,uint256)": FunctionFragment;
    "depositCallback(uint256,uint256,bytes)": FunctionFragment;
    "factory()": FunctionFragment;
    "margins(address,address)": FunctionFragment;
    "positionDescriptor()": FunctionFragment;
    "refundETH()": FunctionFragment;
    "swap((address,address,address,bytes32,bool,uint256,uint256,bool,bool,uint256))": FunctionFragment;
    "swapCallback(uint256,uint256,bytes)": FunctionFragment;
    "sweepToken(address,uint256,address)": FunctionFragment;
    "unwrap(uint256,address)": FunctionFragment;
    "withdraw(address,address,uint256,uint256)": FunctionFragment;
    "wrap(uint256)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "WETH9", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [string, string, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositCallback",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "factory", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "margins",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "positionDescriptor",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "refundETH", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "swap",
    values: [
      {
        recipient: string;
        risky: string;
        stable: string;
        poolId: BytesLike;
        riskyForStable: boolean;
        deltaIn: BigNumberish;
        deltaOut: BigNumberish;
        fromMargin: boolean;
        toMargin: boolean;
        deadline: BigNumberish;
      }
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "swapCallback",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sweepToken",
    values: [string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "unwrap",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [string, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "wrap", values: [BigNumberish]): string;

  decodeFunctionResult(functionFragment: "WETH9", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositCallback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "factory", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "margins", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "positionDescriptor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "refundETH", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "swap", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "swapCallback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sweepToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unwrap", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "wrap", data: BytesLike): Result;

  events: {
    "Deposit(address,address,address,address,address,uint256,uint256)": EventFragment;
    "Swap(address,address,address,bytes32,bool,uint256,uint256,bool,bool)": EventFragment;
    "Withdraw(address,address,address,address,address,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Deposit"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Swap"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Withdraw"): EventFragment;
}

export type DepositEvent = TypedEvent<
  [string, string, string, string, string, BigNumber, BigNumber] & {
    payer: string;
    recipient: string;
    engine: string;
    risky: string;
    stable: string;
    delRisky: BigNumber;
    delStable: BigNumber;
  }
>;

export type SwapEvent = TypedEvent<
  [
    string,
    string,
    string,
    string,
    boolean,
    BigNumber,
    BigNumber,
    boolean,
    boolean
  ] & {
    payer: string;
    recipient: string;
    engine: string;
    poolId: string;
    riskyForStable: boolean;
    deltaIn: BigNumber;
    deltaOut: BigNumber;
    fromMargin: boolean;
    toMargin: boolean;
  }
>;

export type WithdrawEvent = TypedEvent<
  [string, string, string, string, string, BigNumber, BigNumber] & {
    payer: string;
    recipient: string;
    engine: string;
    risky: string;
    stable: string;
    delRisky: BigNumber;
    delStable: BigNumber;
  }
>;

export class SwapManager extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: SwapManagerInterface;

  functions: {
    WETH9(overrides?: CallOverrides): Promise<[string]>;

    deposit(
      recipient: string,
      risky: string,
      stable: string,
      delRisky: BigNumberish,
      delStable: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    depositCallback(
      delRisky: BigNumberish,
      delStable: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    factory(overrides?: CallOverrides): Promise<[string]>;

    margins(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        balanceRisky: BigNumber;
        balanceStable: BigNumber;
      }
    >;

    positionDescriptor(overrides?: CallOverrides): Promise<[string]>;

    refundETH(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    swap(
      params: {
        recipient: string;
        risky: string;
        stable: string;
        poolId: BytesLike;
        riskyForStable: boolean;
        deltaIn: BigNumberish;
        deltaOut: BigNumberish;
        fromMargin: boolean;
        toMargin: boolean;
        deadline: BigNumberish;
      },
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    swapCallback(
      delRisky: BigNumberish,
      delStable: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    sweepToken(
      token: string,
      amountMin: BigNumberish,
      recipient: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    unwrap(
      amountMin: BigNumberish,
      recipient: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    withdraw(
      recipient: string,
      engine: string,
      delRisky: BigNumberish,
      delStable: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    wrap(
      value: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  WETH9(overrides?: CallOverrides): Promise<string>;

  deposit(
    recipient: string,
    risky: string,
    stable: string,
    delRisky: BigNumberish,
    delStable: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  depositCallback(
    delRisky: BigNumberish,
    delStable: BigNumberish,
    data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  factory(overrides?: CallOverrides): Promise<string>;

  margins(
    arg0: string,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & {
      balanceRisky: BigNumber;
      balanceStable: BigNumber;
    }
  >;

  positionDescriptor(overrides?: CallOverrides): Promise<string>;

  refundETH(
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  swap(
    params: {
      recipient: string;
      risky: string;
      stable: string;
      poolId: BytesLike;
      riskyForStable: boolean;
      deltaIn: BigNumberish;
      deltaOut: BigNumberish;
      fromMargin: boolean;
      toMargin: boolean;
      deadline: BigNumberish;
    },
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  swapCallback(
    delRisky: BigNumberish,
    delStable: BigNumberish,
    data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  sweepToken(
    token: string,
    amountMin: BigNumberish,
    recipient: string,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  unwrap(
    amountMin: BigNumberish,
    recipient: string,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  withdraw(
    recipient: string,
    engine: string,
    delRisky: BigNumberish,
    delStable: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  wrap(
    value: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    WETH9(overrides?: CallOverrides): Promise<string>;

    deposit(
      recipient: string,
      risky: string,
      stable: string,
      delRisky: BigNumberish,
      delStable: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    depositCallback(
      delRisky: BigNumberish,
      delStable: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    factory(overrides?: CallOverrides): Promise<string>;

    margins(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        balanceRisky: BigNumber;
        balanceStable: BigNumber;
      }
    >;

    positionDescriptor(overrides?: CallOverrides): Promise<string>;

    refundETH(overrides?: CallOverrides): Promise<void>;

    swap(
      params: {
        recipient: string;
        risky: string;
        stable: string;
        poolId: BytesLike;
        riskyForStable: boolean;
        deltaIn: BigNumberish;
        deltaOut: BigNumberish;
        fromMargin: boolean;
        toMargin: boolean;
        deadline: BigNumberish;
      },
      overrides?: CallOverrides
    ): Promise<void>;

    swapCallback(
      delRisky: BigNumberish,
      delStable: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    sweepToken(
      token: string,
      amountMin: BigNumberish,
      recipient: string,
      overrides?: CallOverrides
    ): Promise<void>;

    unwrap(
      amountMin: BigNumberish,
      recipient: string,
      overrides?: CallOverrides
    ): Promise<void>;

    withdraw(
      recipient: string,
      engine: string,
      delRisky: BigNumberish,
      delStable: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    wrap(value: BigNumberish, overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "Deposit(address,address,address,address,address,uint256,uint256)"(
      payer?: string | null,
      recipient?: string | null,
      engine?: string | null,
      risky?: null,
      stable?: null,
      delRisky?: null,
      delStable?: null
    ): TypedEventFilter<
      [string, string, string, string, string, BigNumber, BigNumber],
      {
        payer: string;
        recipient: string;
        engine: string;
        risky: string;
        stable: string;
        delRisky: BigNumber;
        delStable: BigNumber;
      }
    >;

    Deposit(
      payer?: string | null,
      recipient?: string | null,
      engine?: string | null,
      risky?: null,
      stable?: null,
      delRisky?: null,
      delStable?: null
    ): TypedEventFilter<
      [string, string, string, string, string, BigNumber, BigNumber],
      {
        payer: string;
        recipient: string;
        engine: string;
        risky: string;
        stable: string;
        delRisky: BigNumber;
        delStable: BigNumber;
      }
    >;

    "Swap(address,address,address,bytes32,bool,uint256,uint256,bool,bool)"(
      payer?: string | null,
      recipient?: null,
      engine?: string | null,
      poolId?: BytesLike | null,
      riskyForStable?: null,
      deltaIn?: null,
      deltaOut?: null,
      fromMargin?: null,
      toMargin?: null
    ): TypedEventFilter<
      [
        string,
        string,
        string,
        string,
        boolean,
        BigNumber,
        BigNumber,
        boolean,
        boolean
      ],
      {
        payer: string;
        recipient: string;
        engine: string;
        poolId: string;
        riskyForStable: boolean;
        deltaIn: BigNumber;
        deltaOut: BigNumber;
        fromMargin: boolean;
        toMargin: boolean;
      }
    >;

    Swap(
      payer?: string | null,
      recipient?: null,
      engine?: string | null,
      poolId?: BytesLike | null,
      riskyForStable?: null,
      deltaIn?: null,
      deltaOut?: null,
      fromMargin?: null,
      toMargin?: null
    ): TypedEventFilter<
      [
        string,
        string,
        string,
        string,
        boolean,
        BigNumber,
        BigNumber,
        boolean,
        boolean
      ],
      {
        payer: string;
        recipient: string;
        engine: string;
        poolId: string;
        riskyForStable: boolean;
        deltaIn: BigNumber;
        deltaOut: BigNumber;
        fromMargin: boolean;
        toMargin: boolean;
      }
    >;

    "Withdraw(address,address,address,address,address,uint256,uint256)"(
      payer?: string | null,
      recipient?: string | null,
      engine?: string | null,
      risky?: null,
      stable?: null,
      delRisky?: null,
      delStable?: null
    ): TypedEventFilter<
      [string, string, string, string, string, BigNumber, BigNumber],
      {
        payer: string;
        recipient: string;
        engine: string;
        risky: string;
        stable: string;
        delRisky: BigNumber;
        delStable: BigNumber;
      }
    >;

    Withdraw(
      payer?: string | null,
      recipient?: string | null,
      engine?: string | null,
      risky?: null,
      stable?: null,
      delRisky?: null,
      delStable?: null
    ): TypedEventFilter<
      [string, string, string, string, string, BigNumber, BigNumber],
      {
        payer: string;
        recipient: string;
        engine: string;
        risky: string;
        stable: string;
        delRisky: BigNumber;
        delStable: BigNumber;
      }
    >;
  };

  estimateGas: {
    WETH9(overrides?: CallOverrides): Promise<BigNumber>;

    deposit(
      recipient: string,
      risky: string,
      stable: string,
      delRisky: BigNumberish,
      delStable: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    depositCallback(
      delRisky: BigNumberish,
      delStable: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    factory(overrides?: CallOverrides): Promise<BigNumber>;

    margins(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    positionDescriptor(overrides?: CallOverrides): Promise<BigNumber>;

    refundETH(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    swap(
      params: {
        recipient: string;
        risky: string;
        stable: string;
        poolId: BytesLike;
        riskyForStable: boolean;
        deltaIn: BigNumberish;
        deltaOut: BigNumberish;
        fromMargin: boolean;
        toMargin: boolean;
        deadline: BigNumberish;
      },
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    swapCallback(
      delRisky: BigNumberish,
      delStable: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    sweepToken(
      token: string,
      amountMin: BigNumberish,
      recipient: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    unwrap(
      amountMin: BigNumberish,
      recipient: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    withdraw(
      recipient: string,
      engine: string,
      delRisky: BigNumberish,
      delStable: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    wrap(
      value: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    WETH9(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    deposit(
      recipient: string,
      risky: string,
      stable: string,
      delRisky: BigNumberish,
      delStable: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    depositCallback(
      delRisky: BigNumberish,
      delStable: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    factory(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    margins(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    positionDescriptor(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    refundETH(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    swap(
      params: {
        recipient: string;
        risky: string;
        stable: string;
        poolId: BytesLike;
        riskyForStable: boolean;
        deltaIn: BigNumberish;
        deltaOut: BigNumberish;
        fromMargin: boolean;
        toMargin: boolean;
        deadline: BigNumberish;
      },
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    swapCallback(
      delRisky: BigNumberish,
      delStable: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    sweepToken(
      token: string,
      amountMin: BigNumberish,
      recipient: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    unwrap(
      amountMin: BigNumberish,
      recipient: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    withdraw(
      recipient: string,
      engine: string,
      delRisky: BigNumberish,
      delStable: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    wrap(
      value: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
